name: CI Workflow

on:
  push:
    branches: ["main"]
    paths: ["**.go", "**.html"]

  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "1.21.x"

      - name: Run linter
        uses: golangci/golangci-lint-action@v3

  deploy:
    needs: lint-test
    environment:
      name: live-demo
      url: https://chat.benco.io

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Azure OIDC Login
        uses: azure/login@v1
        with:
          # Note. These are not secrets, they are public values
          client-id: 7027215f-0525-4a7e-9ad4-d9108b36117a
          tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
          subscription-id: 096d0eee-c6d6-4b21-9be9-2063e23bf6f1

      - name: "Run az commands"
        run: |
          az account show
          az group list

      - name: Build container image
        run: make image

      - name: Push container image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ANYONE --password-stdin
          make push

      - name: Deploy to Azure
        run: make deploy
