name: CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  packages: write
  contents: read

env:
  VERSION: latest

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "1.21.x"

      - name: Run linter
        uses: golangci/golangci-lint-action@v3

  deploy:
    needs: lint-test
    environment:
      name: live-demo
      url: https://chat.benco.io

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Build container image
        run: make image

      - name: Push container image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ANYONE --password-stdin
          make push

      - name: Deploy to Azure
        run: make deploy
